### ISSUE TITLE
Add persistance documentation to README

### ISSUE THREAD

**Issue by flexyford** [jasonmit/virtual-each#11]
When we want to persist the positionIndex internally, the position index should remain 'undefined'. Therefore, if we want to reset the viewport to the beginning of the items array, the positionIndex should be set to zero for that instance! Should we maybe consider adding a `reset` attr instead?

**Comment by jasonmit** [comment]
@flexyford I have another proposal instead of implementing `reset` as an attr.

Instead, we could leverage didReceiveAttrs to know what the user switched the position index back to 0 since the `positionIndex` should (I need to validate this) be in the hash of attrs that changed.

If this doesn't behave like I think it does another alternative is implement a full DDAU loop via an action  `positionIndexChanged`.  And changing of position index (scrolling) would invoke that action with the new position and consumers would pass it back the new value back into the component to cause the render.

**Comment by flexyford** [comment]
:+1: for listening to newAttrs on didReceiveAttrs hook

**Comment by jasonmit** [comment]
I vaguely recall something with this strategy in the past that didn't behave as I was expecting.  In any case, I'll spike something for this behavior and test it out.

**Comment by flexyford** [comment]
Hey there 👋 Feel free to close this issue
